---
- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present
    
- name: Var thing
  set_fact: 
    postfix_config: "{{ postfix_config | combine ({item.key : item.value}) }}"
  with_items:
    - { 'key': inet_interfaces, 'value': "{{ postfix_inet_interfaces }}" }
    - { 'key': inet_protocols, 'value': "{{ postfix_inet_protocols }}"}

- name: Update Postfix configuration.
  lineinfile:
    dest: "{{ postfix_config_file }}"
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^{{ item.key }} ="
    mode: 0644
  loop: "{{ lookup('dict', postfix_config) }}"
  notify: restart postfix